using System;
using UnityEngine;

namespace Asteroider
{
    public abstract class ’ŠÛGameboardObject<T, U> : ’ŠÛGameboardObject<T> where T : ’ŠÛGameboardObject<T, U> where U : ’ŠÛGameboardObjectConfig<T>
    {
        [SerializeField] protected U İ’è = null;

        protected virtual void OnValidate()
        {
            Debug.Assert(İ’è != null, $"[{typeof(T).Name}] {name}: İ’è");
        }
    }
    public abstract class ’ŠÛGameboardObject<T> : GameboardObject where T : ’ŠÛGameboardObject<T> {}

    public class GameboardObject : MonoBehaviour
    {
        public EventProxy<GameboardObject> OnDisabled;
        private Action<GameboardObject> onDisabled;

        protected virtual void Awake()
        {
            OnDisabled = new(out onDisabled);
        }

        protected virtual void Start()
        {
            Gameboard’·.Add(this);
        }

        protected virtual void OnDisable() => onDisabled?.Invoke(this);
    }
}
