using UnityEngine;

namespace Asteroider
{
    public abstract class ’ŠÛManager<T, U> : ’ŠÛManager<T> where T : ’ŠÛManager<T, U> where U : ’ŠÛManagerConfig<T>
    {
        [SerializeField] protected U İ’è = null;

        protected virtual void OnValidate()
        {
            Debug.Assert(İ’è != null, $"[{typeof(T).Name}] {name}: İ’è");
        }
    }
    public abstract class ’ŠÛManager<T> : MonoBehaviour where T : ’ŠÛManager<T>
    {
        protected static T Instance { get; private set; } = null;

        virtual protected void OnEnable()
        {
            if (Instance != null) return;

            Instance = (T)this;
        }

        virtual protected void OnDisable()
        {
            if (Instance == this) Instance = null;
        }
    }  
}